# Generated by Django 5.2.12 on 2026-05-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_contactquery_personal'),
        ('builder', '0002_personal'),
    ]

    operations = [
    ]
