# Generated by Django 5.2.12 on 2026-05-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_contactquery_status'),
        ('builder', '0003_merge_0002_contactquery_personal_0002_personal'),
    ]

    operations = [
    ]
